name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd docker && docker build . --file Dockerfile --tag joshuasu/oneindex:$COMMIT_SHA
           docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
           docker push joshuasu/oneindex:$COMMIT_SHA
           docker tag joshuasu/oneindex:$COMMIT_SHA joshuasu/oneindex:latest
           docker push joshuasu/oneindex:latest
